#!/bin/bash
export executable="build/xmod"
ls "$executable" || make || echo "Error: Could not find program executable."
cd test/tests || echo "Error: Could not access test folder."
export executable="../../build/xmod"

export no_failed=0
export no_passed=0
no_suites_failed=0

function xmod() {
  $executable ${@:2} >&/dev/null
  if [ $? -ne "$1" ]; then
    printf "\e[1;31mFAILED\n\e[0m"
    ((no_failed++))
  else
    printf "\e[1;32mPASSED\n\e[0m"
    ((no_passed++))
  fi
  return
}

export -f xmod

function test_name() {
  printf "Test %s - %-80s" "$1" "$2"
}

export -f test_name
for i in {00..00}; do
  echo "Running test suite $i"
  export no_failed=0
  export no_passed=0
  ./test"$i"
  ret=$?
  if [ $ret != 0 ]; then
    ((no_failed += ret))
    ((++no_suites_failed))
  fi

  if [ "$no_failed" != 0 ]; then
    printf "\e[1;31mFAILED %d tests from %d suites\n\e[0m" "$no_failed" "$no_suites_failed"
  else
    printf "\e[1;32mALL TESTS PASSED\n\e[0m"
  fi
done
