name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
       working-directory: ./project

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: test
      run: ./test.sh bare_minimum bare_minimum/level0_1/file5.txt
