name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
       working-directory: $PWD/project

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: test
      run: echo $PWD
